language: scala
dist: xenial
jdk: openjdk8
script:
- sbt -Dscala.version=2.13.2 sql/compile ";core/publishLocal;sketch/publishLocal;tags/publishLocal;launcher/publishLocal;kvstore/publishLocal;network-common/publishLocal;network-shuffle/publishLocal;unsafe/publishLocal;catalyst/publishLocal;sql/publishLocal"
